/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tiketBioskop;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class tiketBioskop extends javax.swing.JFrame {
  int reguler,ultra,gold,harga,beli,total,bayar,kembali;
    /**
     * Creates new form tiketBioskop
     */
    public tiketBioskop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel3 = new javax.swing.JLabel();
        rb_gold = new javax.swing.JRadioButton();
        rb_ultra = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rb_reguler = new javax.swing.JRadioButton();
        kursi = new javax.swing.JComboBox<>();
        hargaSatuan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        namaLengkap = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jumlahBeli = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        totalBayar = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jumlahBayar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        kembalian = new javax.swing.JTextField();
        btnInput = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        btnInput1 = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Penjualan Tiket Bioskop");

        buttonGroup1.add(rb_gold);
        rb_gold.setText("Gold");
        rb_gold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_goldActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb_ultra);
        rb_ultra.setText("Ultra XD");
        rb_ultra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_ultraActionPerformed(evt);
            }
        });

        jLabel4.setText("Harga Satuan");

        jLabel2.setText("Jenis Tiket");

        jLabel1.setText("Kursi");

        buttonGroup1.add(rb_reguler);
        rb_reguler.setText("Reguler");
        rb_reguler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_regulerActionPerformed(evt);
            }
        });

        kursi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "A", "B", "C", "D" }));
        kursi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursiActionPerformed(evt);
            }
        });

        hargaSatuan.setEditable(false);

        jLabel7.setText("Nama Lengkap");

        namaLengkap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaLengkapActionPerformed(evt);
            }
        });

        jLabel5.setText("Jumlah Beli");

        jumlahBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahBeliActionPerformed(evt);
            }
        });
        jumlahBeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jumlahBeliKeyReleased(evt);
            }
        });

        jLabel6.setText("Total Bayar");

        totalBayar.setEditable(false);

        jLabel8.setText("Jumlah Bayar");

        jumlahBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahBayarActionPerformed(evt);
            }
        });

        jLabel9.setText("Kembalian");

        kembalian.setEditable(false);

        btnInput.setText("Input Data");
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        btnInput1.setText("Print Data");
        btnInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInput1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(totalBayar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hargaSatuan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rb_ultra)
                                .addGap(18, 18, 18)
                                .addComponent(rb_gold))
                            .addComponent(jumlahBayar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(rb_reguler))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(kembalian)
                                    .addComponent(jumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(namaLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnInput)
                        .addGap(18, 18, 18)
                        .addComponent(btnInput1)
                        .addGap(18, 18, 18)
                        .addComponent(keluar))
                    .addComponent(kursi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(namaLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(kursi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2))
                    .addComponent(rb_ultra)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rb_gold)
                        .addComponent(rb_reguler)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hargaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jumlahBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(totalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jumlahBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInput)
                    .addComponent(keluar)
                    .addComponent(btnInput1))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        int pilih = JOptionPane.showConfirmDialog(null , "Yakin mau keluar?", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION);
        if (pilih == JOptionPane.OK_OPTION) {
            System.exit(0);
        } else {
           JOptionPane.getRootFrame();
        }
    }//GEN-LAST:event_keluarActionPerformed

    private void namaLengkapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaLengkapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaLengkapActionPerformed

    private void kursiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursiActionPerformed
        String result = kursi.getSelectedItem().toString();
        
        switch(result) {
            case "Pilih": 
                buttonGroup1.clearSelection();
                hargaSatuan.setText("");
                break;
            case "A": 
                reguler=50000;
                ultra=70000;
                gold=90000;
                break;
            case "B": 
                reguler=45000;
                ultra=65000;
                gold=85000;
                break;
            case "C": 
                reguler=40000;
                ultra=60000;
                gold=80000;
                break;
            case "D": 
                reguler=40000;
                ultra=60000;
                gold=80000;
                break;
            default:
                JOptionPane.showMessageDialog(rootPane, "Kursi tidak valid");
                break;
        }
    }//GEN-LAST:event_kursiActionPerformed

    private void rb_regulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_regulerActionPerformed
        if(rb_reguler.isSelected()) {
            hargaSatuan.setText(String.valueOf(reguler));
        }
    }//GEN-LAST:event_rb_regulerActionPerformed

    private void rb_goldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_goldActionPerformed
        if(rb_gold.isSelected()) {
            hargaSatuan.setText(String.valueOf(gold));
        }
    }//GEN-LAST:event_rb_goldActionPerformed

    private void rb_ultraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_ultraActionPerformed
        if(rb_ultra.isSelected()) {
            hargaSatuan.setText(String.valueOf(ultra));
        }
    }//GEN-LAST:event_rb_ultraActionPerformed

    private void jumlahBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahBeliActionPerformed
        beli = Integer.parseInt(jumlahBeli.getText());
        harga = Integer.parseInt(hargaSatuan.getText());
        total = harga * beli;
        totalBayar.setText(String.valueOf(total));
    }//GEN-LAST:event_jumlahBeliActionPerformed

    private void jumlahBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahBayarActionPerformed
        beli = Integer.parseInt(jumlahBayar.getText());
        kembali = Integer.parseInt(totalBayar.getText());
        total = beli - kembali;
        kembalian.setText(String.valueOf(total));
    }//GEN-LAST:event_jumlahBayarActionPerformed

    private void jumlahBeliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahBeliKeyReleased
        int a,b,c;
        a = Integer.parseInt(jumlahBeli.getText());
        b = Integer.parseInt(hargaSatuan.getText());
        c = a * b;
        totalBayar.setText(String.valueOf(""+c));
    }//GEN-LAST:event_jumlahBeliKeyReleased

    private void btnInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInput1ActionPerformed
        JFrame frame = new JFrame();
        String tampil[] = {
            "Nama Lengkap : "+namaLengkap.getText(),
            "Kursi : "+kursi.getSelectedItem().toString(),
            "Harga Satuan : "+hargaSatuan.getText(),
            "Jumlah Beli : "+jumlahBeli.getText(),
            "Total Bayar : "+totalBayar.getText(),
            "Jumlah Bayar : "+jumlahBayar.getText(),
            "Kembalian : "+kembalian.getText(),
        };
        JOptionPane.showMessageDialog(frame, tampil);
    }//GEN-LAST:event_btnInput1ActionPerformed

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
        // TODO add your handling code here:
        namaLengkap.setText("");
        hargaSatuan.setText("");
        totalBayar.setText("");
        jumlahBayar.setText("");
        kembalian.setText("");
        jumlahBeli.setText("");
        buttonGroup1.clearSelection();
        kursi.setSelectedItem("Pilih");
    }//GEN-LAST:event_btnInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tiketBioskop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tiketBioskop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tiketBioskop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tiketBioskop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tiketBioskop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInput;
    private javax.swing.JButton btnInput1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField hargaSatuan;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jumlahBayar;
    private javax.swing.JTextField jumlahBeli;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField kembalian;
    private javax.swing.JComboBox<String> kursi;
    private javax.swing.JTextField namaLengkap;
    private javax.swing.JRadioButton rb_gold;
    private javax.swing.JRadioButton rb_reguler;
    private javax.swing.JRadioButton rb_ultra;
    private javax.swing.JTextField totalBayar;
    // End of variables declaration//GEN-END:variables
}
